# Generated by Django 4.1.3 on 2022-12-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listing_category_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('TENN', 'Tennis'), ('FOOT', 'Football'), ('BASE', 'Baseball'), ('BASK', 'Basketball'), ('HOCK', 'Hockey'), ('OTHER', 'Other Sports')], default='TENN', max_length=64),
        ),
    ]
