# Generated by Django 4.1.3 on 2022-12-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_starting_bid_listing_bid_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='on_watchlist',
        ),
    ]
